# Generated by Django 2.2 on 2019-05-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Price', models.FloatField()),
                ('Year', models.DateField()),
                ('edition', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='')),
                ('Writer_name', models.CharField(max_length=50)),
                ('Book_name', models.CharField(max_length=50)),
                ('Book_type', models.IntegerField()),
                ('Book_category', models.CharField(max_length=150)),
            ],
        ),
    ]
