# Generated by Django 2.2 on 2019-05-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_secondhand_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookStore_name', models.CharField(max_length=50)),
                ('out_of_stock', models.BooleanField()),
                ('Book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
            ],
        ),
    ]
