# Generated by Django 2.2 on 2019-05-29 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_systemadmin'),
        ('books', '0003_new_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_of_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.secondhand_books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.User')),
            ],
        ),
    ]
