# Generated by Django 2.2 on 2019-05-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_readingevent'),
        ('books', '0005_newbooks_of_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookStore_name', models.CharField(max_length=50)),
                ('out_of_stock', models.BooleanField()),
                ('Book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.BookStore')),
            ],
        ),
        migrations.RemoveField(
            model_name='newbooks_of_user',
            name='newbook',
        ),
        migrations.RemoveField(
            model_name='newbooks_of_user',
            name='newuser',
        ),
        migrations.DeleteModel(
            name='new_books',
        ),
        migrations.DeleteModel(
            name='newBooks_of_user',
        ),
    ]
