# Generated by Django 2.2 on 2019-05-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('u_type', models.IntegerField()),
                ('names_of_books', models.DateField()),
                ('categories', models.DateField()),
                ('phone', models.CharField(max_length=14)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
