# Generated by Django 2.2 on 2019-05-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('system_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
