# Generated by Django 2.2 on 2019-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20190530_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemadmin',
            name='system_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
