# Generated by Django 2.2 on 2019-05-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_auto_20190531_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
    ]
