# Generated by Django 2.2 on 2019-05-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_remove_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='fffRole',
        ),
    ]
