# Generated by Django 2.2 on 2019-05-31 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_auto_20190531_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='u_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Role'),
        ),
        migrations.DeleteModel(
            name='fffRole',
        ),
    ]
