# Generated by Django 2.2 on 2019-05-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('bookstore_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=1000)),
            ],
        ),
    ]
