# Generated by Django 2.2 on 2019-05-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('bookstore_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Bookstore',
        ),
    ]
