# Generated by Django 2.2 on 2019-05-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_systemadmin'),
        ('bookstore', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('bookstore_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.SystemAdmin')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
