# Generated by Django 2.2 on 2019-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_readingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='bookstore_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
