# Generated by Django 2.2 on 2019-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20190530_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingevent',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
