# Generated by Django 2.2 on 2019-05-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reader', '0002_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.DateField(max_length=1000)),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.User')),
            ],
        ),
    ]
