# Generated by Django 2.2 on 2019-05-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.DateField(max_length=1000)),
                ('Writer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.Writer')),
            ],
        ),
    ]
