# Generated by Django 2.2 on 2019-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0004_auto_20190530_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='bio',
            field=models.TextField(max_length=1000),
        ),
    ]
